version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck
  exclusions:
    rules:
      # テストファイルの errcheck は緩める
      - path: "_test\\.go"
        linters:
          - errcheck
