# golangci-lint v1.64.x 対応設定
run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

issues:
  exclude-rules:
    # テストファイルの errcheck は緩める
    - path: "_test\\.go"
      linters:
        - errcheck
